services:
  db:
    image: mongo:latest
    container_name: book-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bookstore-network

  backend:
    build: .
    container_name: book-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
    networks:
      - bookstore-network

  frontend:
    build: ./frontend
    container_name: book-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bookstore-network

volumes:
  mongo_data:


networks:
  bookstore-network:
    driver: bridge
